## 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

c:\users\xiaolinzi\miniconda3\envs\py36_ml\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffle_indexes = np.random.permutation(len(X))

In [9]:
shuffle_indexes

array([ 86, 102, 148,  20, 118,  52,  98,  25, 147, 112, 104,  73,  12,
        16,  95,  42,  35, 108,  50,  46,  99, 121,  36,  87, 139,  22,
        37, 130,  63,  49,  15, 146, 100,  60,  14, 135,   4, 132, 105,
        75, 129,  96,  85, 145,  53,  62, 123, 103, 117,  48,  59,  64,
        93,  18, 127,  10,  45,  17,  24,  29,  88,   8, 115,  92, 125,
        41,  84,  47,  76, 138,  97, 134, 142, 106,   2, 128,  70,  23,
        30,  56, 113,  40,  65,  13, 124,  77,   5,  34,  81,  67,   7,
        27,  54,   1,  21,  31,   9,  89,  61,  94, 131,  26,  55,  90,
        58,  32, 101,  19,  66, 126,  39,  79, 136,  71, 111, 116, 133,
       140,  68,  91,  80, 122,  43,   6,  83, 137,  57, 141,   3, 144,
        74,  38, 109, 110, 143,  51, 119,   0,  78,  82, 114, 149, 120,
        72,  69, 107,  11,  28,  33,  44])

In [10]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [11]:
test_size

30

In [12]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [15]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [16]:
from playML.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [19]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [20]:
from playML.kNN import KNNClassifier

In [21]:
my_knn_clf = KNNClassifier(k=3)

In [22]:
my_knn_clf.fit(X_train,y_train)

KNN(k=3)

In [23]:
y_predict = my_knn_clf.predict(X_test)

In [24]:
y_predict

array([2, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0,
       1, 2, 2, 1, 0, 1, 0, 1])

In [25]:
np.sum(y_predict == y_test)

28

In [26]:
np.sum(y_predict == y_test) / len(y_test)

0.9333333333333333

## sklearn 中的 train_test_split

In [27]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=666)

In [32]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [33]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
