### 合并操作

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [3]:
x

array([1, 2, 3])

In [4]:
y

array([3, 2, 1])

In [5]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [6]:
z = np.array([666,666,666])

In [7]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [8]:
A = np.arange(1,7).reshape(2,-1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [12]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
A2 = np.concatenate([A,z.reshape(1,-1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [16]:
np.vstack([A,z]) # 垂直方向拼接

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [17]:
B = np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [19]:
np.hstack([A,B]) # 水平方向拼接

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [20]:
z

array([666, 666, 666])

In [24]:
np.hstack([A,np.array([[2],[3]])])

array([[1, 2, 3, 2],
       [4, 5, 6, 3]])

### 分割操作

In [25]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x1,x2,x3 = np.split(x,[3,7])

In [27]:
x1

array([0, 1, 2])

In [28]:
x2

array([3, 4, 5, 6])

In [29]:
x3

array([7, 8, 9])

In [30]:
x1,x2 = np.split(x,[5])

In [31]:
x1

array([0, 1, 2, 3, 4])

In [32]:
x2

array([5, 6, 7, 8, 9])

In [34]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
A1,A2 = np.split(A,[2])

In [36]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [37]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
A1,A2 = np.split(A,[2],axis=1)

In [39]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [40]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [41]:
upper,lower = np.vsplit(A,[2])

In [42]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
left,right = np.hsplit(A,[2])

In [45]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [46]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [47]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
X,y = np.hsplit(data,[-1])

In [49]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [50]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [51]:
y[:,0]

array([ 3,  7, 11, 15])