## 聚合操作

In [32]:
import numpy as np

L = np.random.random(100)

In [33]:
L

array([0.58651986, 0.8329717 , 0.04694034, 0.68793636, 0.79798573,
       0.90101388, 0.03167854, 0.02911149, 0.65968571, 0.46164994,
       0.11498331, 0.1556683 , 0.76496217, 0.06536516, 0.95114103,
       0.4607744 , 0.38689078, 0.99529505, 0.00661197, 0.62896515,
       0.08425292, 0.7841694 , 0.45131813, 0.15828012, 0.83031291,
       0.25699516, 0.02336548, 0.05153186, 0.49010328, 0.63294717,
       0.83295025, 0.90621146, 0.6518583 , 0.8305588 , 0.78557097,
       0.00766495, 0.88486134, 0.6509911 , 0.39853764, 0.37150048,
       0.61775362, 0.04860848, 0.72529624, 0.43670202, 0.72389934,
       0.67726424, 0.3103147 , 0.53166467, 0.95611282, 0.6078876 ,
       0.125183  , 0.10225316, 0.79750918, 0.6866896 , 0.68406181,
       0.40787726, 0.48820812, 0.94009717, 0.31002061, 0.90544872,
       0.02887916, 0.71381252, 0.35029971, 0.95060301, 0.51164383,
       0.68997701, 0.02859882, 0.87872914, 0.58487119, 0.2167855 ,
       0.81772158, 0.88032449, 0.93970432, 0.78390234, 0.46395

In [34]:
sum(L)

50.798337335040664

In [35]:
np.sum(L)

50.79833733504065

In [36]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

271 ms ± 9.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.31 ms ± 42.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
a = np.random.rand(10)
a

array([0.28972375, 0.72636934, 0.17090176, 0.8645799 , 0.64149186,
       0.19153523, 0.1909504 , 0.97993032, 0.55423765, 0.04779078])

In [38]:
np.min(big_array)

1.375324594099503e-06

In [39]:
np.max(big_array)

0.999999469353056

In [40]:
big_array.min()

1.375324594099503e-06

In [41]:
big_array.max()

0.999999469353056

In [42]:
big_array.sum()

499805.4725266022

In [43]:
X = np.arange(16).reshape((4,-1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
np.sum(X)

120

In [45]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [46]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [47]:
np.prod(X) # 所有元素的乘积操作

0

In [48]:
np.prod(X + 1)

2004189184

In [49]:
np.mean(X)

7.5

In [50]:
np.median(X)

7.5

In [51]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [53]:
np.median(v)

2.0

In [54]:
np.percentile(big_array,q=50)

0.499843446823636

In [55]:
np.median(big_array)

0.499843446823636

In [56]:
np.percentile(big_array,q=100)

0.999999469353056

In [57]:
np.max(big_array)

0.999999469353056

In [58]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

1.375324594099503e-06
0.2495381081871886
0.499843446823636
0.7497057279924239
0.999999469353056


In [59]:
np.var(big_array) # 方差

0.08335235004863661

In [60]:
np.std(big_array) # 标准差

0.2887080706330126

In [61]:
x = np.random.normal(0,1,size=1000000)

In [62]:
np.mean(x)

-0.00095643502959699

In [63]:
np.std(x)

0.9996298516890022