## 索引

In [9]:
import numpy as np

In [10]:
x = np.random.normal(0,1,size=1000000)

In [11]:
np.min(x)

-4.832051378504327

In [12]:
np.argmin(x)

483636

In [13]:
x[593626]

-0.22305176652429454

In [14]:
np.argmax(x)

521550

In [15]:
x[71583]

0.1199670359775834

In [16]:
np.max(x)

4.8250928244731375

## 排序和使用索引

In [17]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)
x

array([ 3,  2,  5,  0, 11,  1,  9, 14, 12, 15, 13,  8,  4,  6, 10,  7])

In [20]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
x

array([ 3,  2,  5,  0, 11,  1,  9, 14, 12, 15, 13,  8,  4,  6, 10,  7])

In [22]:
x.sort()

In [23]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
X = np.random.randint(10,size=(4,4))
X

array([[3, 3, 8, 2],
       [9, 6, 8, 2],
       [8, 7, 5, 6],
       [9, 9, 8, 0]])

In [25]:
np.sort(X)

array([[2, 3, 3, 8],
       [2, 6, 8, 9],
       [5, 6, 7, 8],
       [0, 8, 9, 9]])

In [26]:
np.sort(X,axis=1)

array([[2, 3, 3, 8],
       [2, 6, 8, 9],
       [5, 6, 7, 8],
       [0, 8, 9, 9]])

In [27]:
np.sort(X,axis=0)

array([[3, 3, 5, 0],
       [8, 6, 8, 2],
       [9, 7, 8, 2],
       [9, 9, 8, 6]])

In [28]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
np.random.shuffle(x)
x

array([ 8,  6,  0, 11, 14,  2,  3, 13,  5, 15,  1, 10,  4, 12,  7,  9])

In [30]:
np.argsort(x)

array([ 2, 10,  5,  6, 12,  8,  1, 14,  0, 15, 11,  3, 13,  7,  4,  9],
      dtype=int64)

In [31]:
x[np.argsort(x)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  8,  7,  6,  5,  9, 15, 10, 14, 12, 11, 13])

In [33]:
np.partition(x,6)

array([ 2,  1,  0,  3,  4,  5,  6,  7,  8,  9, 15, 10, 14, 12, 11, 13])

In [34]:
np.argpartition(x,6)

array([ 5, 10,  2,  6, 12,  8,  1, 14,  0, 15,  9, 11,  4, 13,  3,  7],
      dtype=int64)

In [35]:
x[np.argpartition(x,6)]

array([ 2,  1,  0,  3,  4,  5,  6,  7,  8,  9, 15, 10, 14, 12, 11, 13])

In [36]:
X

array([[3, 3, 8, 2],
       [9, 6, 8, 2],
       [8, 7, 5, 6],
       [9, 9, 8, 0]])

In [37]:
np.argsort(X,axis=1)

array([[3, 0, 1, 2],
       [3, 1, 2, 0],
       [2, 3, 1, 0],
       [3, 2, 0, 1]], dtype=int64)

In [38]:
np.argsort(X,axis=0)

array([[0, 0, 2, 3],
       [2, 1, 0, 0],
       [1, 2, 1, 1],
       [3, 3, 3, 2]], dtype=int64)

In [39]:
np.argpartition(X,2,axis=1)

array([[3, 1, 0, 2],
       [3, 1, 2, 0],
       [2, 3, 1, 0],
       [3, 2, 1, 0]], dtype=int64)

In [40]:
np.argpartition(X,2,axis=0)

array([[0, 0, 2, 3],
       [2, 1, 1, 1],
       [1, 2, 0, 0],
       [3, 3, 3, 2]], dtype=int64)